baseURL = 'https://aibaniz.github.io/calligraphy-across-caliphates/'
languageCode = 'en-us'
title = 'Calligraphy Across the Caliphates'
enableRobotsTXT = true

[module]
  disable = true

[params]
  custom_css = ["custom.css"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Allows inline HTML in Markdown

[outputs]
  home = ["HTML"]
